### ISSUE TITLE
OutOfMemoryError when trying to train FCN32s on my own dataset

### ISSUE THREAD

**Issue by mrteera** [wkentaro/fcn#103]
I am trying to train FCN32s on my own dataset. The training set consists of 135 images. The image size would be 1600x1200, 1280x960, and 1024x768. In `train_fcn32s.py`, I use the original `shared_mem` value which is `10 ** 7` for `chainer.iterators.MultiprocessIterator`. 
```
    iter_train = chainer.iterators.MultiprocessIterator(
        dataset_train, batch_size=1, shared_mem=10 ** 7)
```
But I have this warning message:

```
Please set shared_mem option for MultiprocessIterator.
Expect shared memory size: 12000000 bytes.
Actual shared memory size: 1000000 bytes.
```
And this error message:
```
train:   7%|##5                               | 74/1000 [01:37<20:20,  1.32s/it]Traceback (most recent call last):
  File "train_fcn32s.py", line 96, in <module>
    main()
  File "train_fcn32s.py", line 92, in main
    trainer.train()
  File "/usr/local/lib/python2.7/dist-packages/fcn/trainer.py", line 198, in train
    loss.backward()
  File "/usr/local/lib/python2.7/dist-packages/chainer/variable.py", line 878, in backward
    self._backward_main(retain_grad)
  File "/usr/local/lib/python2.7/dist-packages/chainer/variable.py", line 979, in _backward_main
    target_input_indexes, out_grad, in_grad)
  File "/usr/local/lib/python2.7/dist-packages/chainer/function_node.py", line 514, in backward_accumulate
    gxs = self.backward(target_input_indexes, grad_outputs)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/activation/relu.py", line 49, in backward
    return ReLUGrad2(y).apply((gy[0],))
  File "/usr/local/lib/python2.7/dist-packages/chainer/function_node.py", line 245, in apply
    outputs = self.forward(in_data)
  File "/usr/local/lib/python2.7/dist-packages/chainer/function_node.py", line 337, in forward
    return self.forward_gpu(inputs)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/activation/relu.py", line 80, in forward_gpu
    'relu_bwd')(self.b, inputs[0])
  File "cupy/core/elementwise.pxi", line 566, in cupy.core.core.ElementwiseKernel.__call__
  File "cupy/core/elementwise.pxi", line 409, in cupy.core.core._get_out_args_with_params
  File "cupy/core/core.pyx", line 95, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 441, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 915, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 936, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 693, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 748, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
cupy.cuda.memory.OutOfMemoryError: out of memory to allocate 955444224 bytes (total 11433940992 bytes)
```
My GPU is NVIDIA 1080 Ti with 11 GB memory but the training process consume all of its memory. I have tried to increase the `shared_mem` value but I still get the same memory allocation issue. Could you please give me an idea about this issue? Or how should I properly configure the `shared_mem` value?

**Comment by mrteera** [comment]
I think I just need to resize the images beforehand. I'm sorry for creating an issue.
