### ISSUE TITLE
Unable to run the new train_fcn32s

### ISSUE THREAD

**Issue by mrteera** [wkentaro/fcn#106]
I have got this error when I was trying to run the new train_fcn32s.

```
/usr/local/lib/python2.7/dist-packages/cupy/core/fusion.py:659: FutureWarning: cupy.core.fusion is experimental. The interface can change in the future.
  util.experimental('cupy.core.fusion')
# -----------------------------------------------------------------------------
{'gpu': 0,
 'interval_eval': 4000,
 'interval_print': 20,
 'lr': 1e-10,
 'max_iteration': 100000,
 'model': 'FCN32s',
 'momentum': 0.99,
 'out': '/root/fcn/juanjo_fcn/examples/voc/logs/20180131_075839',
 'timestamp': '2018-01-31T07:58:39.807105',
 'weight_decay': 0.0005}
# -----------------------------------------------------------------------------
Exception in main training loop: Unsupported dtype object
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/trainer.py", line 304, in run
    update()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/updaters/standard_updater.py", line 154, in update_core
    in_arrays = self.converter(batch, self.device)
  File "/usr/local/lib/python2.7/dist-packages/chainer/dataset/convert.py", line 110, in concat_examples
    return to_device(device, _concat_arrays(batch, padding))
  File "/usr/local/lib/python2.7/dist-packages/chainer/dataset/convert.py", line 36, in to_device
    return cuda.to_gpu(x, device)
  File "/usr/local/lib/python2.7/dist-packages/chainer/backends/cuda.py", line 277, in to_gpu
    return _array_to_gpu(array, device_, stream)
  File "/usr/local/lib/python2.7/dist-packages/chainer/backends/cuda.py", line 322, in _array_to_gpu
    return cupy.asarray(array)
  File "/usr/local/lib/python2.7/dist-packages/cupy/creation/from_data.py", line 61, in asarray
    return core.array(a, dtype, False)
  File "cupy/core/core.pyx", line 2085, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2116, in cupy.core.core.array
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/fcn/juanjo_fcn/examples/voc/train_fcn32s.py", line 144, in <module>
    main()
  File "/root/fcn/juanjo_fcn/examples/voc/train_fcn32s.py", line 140, in main
    trainer.run()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/trainer.py", line 318, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/trainer.py", line 304, in run
    update()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/updaters/standard_updater.py", line 154, in update_core
    in_arrays = self.converter(batch, self.device)
  File "/usr/local/lib/python2.7/dist-packages/chainer/dataset/convert.py", line 110, in concat_examples
    return to_device(device, _concat_arrays(batch, padding))
  File "/usr/local/lib/python2.7/dist-packages/chainer/dataset/convert.py", line 36, in to_device
    return cuda.to_gpu(x, device)
  File "/usr/local/lib/python2.7/dist-packages/chainer/backends/cuda.py", line 277, in to_gpu
    return _array_to_gpu(array, device_, stream)
  File "/usr/local/lib/python2.7/dist-packages/chainer/backends/cuda.py", line 322, in _array_to_gpu
    return cupy.asarray(array)
  File "/usr/local/lib/python2.7/dist-packages/cupy/creation/from_data.py", line 61, in asarray
    return core.array(a, dtype, False)
  File "cupy/core/core.pyx", line 2085, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2116, in cupy.core.core.array
ValueError: Unsupported dtype object
```

I'm using Chainer and CuPy from master branch. Which Chainer version are you using?
(requirements.txt specified only `chainer>=2.0.0`)

**Comment by mrteera** [comment]
I got it. I'm also need to update https://github.com/wkentaro/fcn/blob/master/fcn/datasets/transforms.py
