### ISSUE TITLE
I want to train my datasets but get the following errors, what should I do? 

### ISSUE THREAD

**Issue by upuil** [wkentaro/fcn#108]
(tet-fcn) pu@pu:~/Downloads/tet-fcn/fcn/examples/voc$ **./train_fcn32s.py --gpu 0**
/home/pu/Downloads/tet-fcn/local/lib/python2.7/site-packages/cupy/core/fusion.py:659: FutureWarning: cupy.core.fusion is experimental. The interface can change in the future.
  util.experimental('cupy.core.fusion')
/home/pu/Downloads/tet-fcn/local/lib/python2.7/site-packages/chainer-4.0.0b2-py2.7.egg/chainer/backends/cuda.py:88: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cupy-with-cudnn-and-nccl).
  'cuDNN is not enabled.\n'
train:   0%|                                         | 0/100000 [00:00<?, ?it/s]Exception in thread prefetch_loop:[iteration=00000000]:   0%|                       | 0/736 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pu/Downloads/tet-fcn/local/lib/python2.7/site-packages/chainer-4.0.0b2-py2.7.egg/chainer/iterators/multiprocess_iterator.py", line 330, in _run
    alive = self._task()
  File "/home/pu/Downloads/tet-fcn/local/lib/python2.7/site-packages/chainer-4.0.0b2-py2.7.egg/chainer/iterators/multiprocess_iterator.py", line 349, in _task
    data_all = future.get(_response_time)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
**IOError: [Errno 2] No such file or directory: '/home/pu/data/datasets/VOC/VOCdevkit/VOC2012/JPEGImages/2007_000033.jpg'**

**Comment by wkentaro** [comment]
Please run `./download_datasets.py` following the README: https://github.com/wkentaro/fcn#training
