### ISSUE TITLE
question!,help!

### ISSUE THREAD

**Issue by jinhang** [wkentaro/fcn#38]
Hello, read your code, don't know how to use your code is, oneself also in the study of FCN,Specific how to use the code.than you for you research!

**Comment by wkentaro** [comment]
Do you have question about the scripts in README.rst? It won't work?

**Comment by jinhang** [comment]
when i run the command: sudo python fcn_forward.py --img-files sample.jpg 
MY error: 
File "fcn_forward.py", line 133, in <module>
    main()
  File "fcn_forward.py", line 122, in main
    forwarding = Forwarding(gpu, chainermodel)
  File "fcn_forward.py", line 50, in __init__
    S.load_hdf5(chainermodel, self.model)
  File "/usr/local/lib/python2.7/dist-packages/chainer/serializers/hdf5.py", line 119, in load_hdf5
    with h5py.File(filename, 'r') as f:
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-build-F9Z8Ra/h5py/h5py/_objects.c:2682)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-build-F9Z8Ra/h5py/h5py/_objects.c:2640)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/tmp/pip-build-F9Z8Ra/h5py/h5py/h5f.c:1928)
IOError: Unable to open file (Unable to find a valid file signature)

**Comment by wkentaro** [comment]
How do you install this package? `python setup.py develop`? `python setup.py install`? or `pip install fcn`?

**Comment by jinhang** [comment]
my command : python setup.py install

**Comment by jinhang** [comment]
What should I do now? thanks

**Comment by jinhang** [comment]
I'm not understand about here：
```
You need to download pascal VOC2012 dataset from `here <http://host.robots.ox.ac.uk/pascal/VOC/voc2012/>`_,
and install it as below construction::

  - fcn - data - pascal - VOC2012 -- JPEGImages
                                   - SegmentationClass
                                   - ...
```

**Comment by wkentaro** [comment]
> I'm not understand about here：

It means you should install VOC2012 dataset to the `data` directory.

**Comment by wkentaro** [comment]
> my command : python setup.py install

https://github.com/wkentaro/fcn#for-beginners won't work?

**Comment by jinhang** [comment]
yes! It won't work! it's error is :+1: 
` python fcn_forward.py --img-files sample.jpg `
error: 
```
File "fcn_forward.py", line 133, in 
main()
File "fcn_forward.py", line 122, in main
forwarding = Forwarding(gpu, chainermodel)
File "fcn_forward.py", line 50, in init
S.load_hdf5(chainermodel, self.model)
File "/usr/local/lib/python2.7/dist-packages/chainer/serializers/hdf5.py", line 119, in load_hdf5
with h5py.File(filename, 'r') as f:
File "/usr/local/lib/python2.7/dist-packages/h5py/hl/files.py", line 272, in __init_
fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 92, in make_fid
fid = h5f.open(name, flags, fapl=fapl)
File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-build-F9Z8Ra/h5py/h5py/_objects.c:2682)
File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-build-F9Z8Ra/h5py/h5py/_objects.c:2640)
File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/tmp/pip-build-F9Z8Ra/h5py/h5py/h5f.c:1928)
IOError: Unable to open file (Unable to find a valid file signature)
```

**Comment by jinhang** [comment]
work-station@workstation-HP-Z440-Workstation:~/FCN/fcn-master/scripts$ sudo python fcn_forward.py --img-files sample.jpg 
[sudo] password for work-station: 
/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/home/work-station/FCN/fcn-master/scripts/sample.jpg:
 - resizing_scale: 0.894684897365
Traceback (most recent call last):
  File "fcn_forward.py", line 133, in <module>
    main()
  File "fcn_forward.py", line 124, in main
    img, label = forwarding.forward_img_file(img_file)
  File "fcn_forward.py", line 68, in forward_img_file
    self.model(x)
  File "/usr/local/lib/python2.7/dist-packages/fcn-3.0.0-py2.7.egg/fcn/models/fcn8s.py", line 118, in __call__
    h = self.upscore2(score_fr)
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/connection/deconvolution_2d.py", line 96, in __call__
    self.outsize, self.use_cudnn)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/connection/deconvolution_2d.py", line 317, in deconvolution_2d
    return func(x, W, b)
  File "/usr/local/lib/python2.7/dist-packages/chainer/function.py", line 123, in __call__
    outputs = self.forward(in_data)
  File "/usr/local/lib/python2.7/dist-packages/chainer/function.py", line 227, in forward
    return self.forward_gpu(inputs)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/connection/deconvolution_2d.py", line 160, in forward_gpu
    gcol, self.sy, self.sx, self.ph, self.pw, self.outh, self.outw)
  File "/usr/local/lib/python2.7/dist-packages/chainer/utils/conv.py", line 114, in col2im_gpu
    h, w, out_h, out_w, kh, kw, sy, sx, ph, pw, img)
  File "cupy/core/elementwise.pxi", line 545, in cupy.core.core.ElementwiseKernel.__call__ (cupy/core/core.cpp:34370)
  File "cupy/util.pyx", line 36, in cupy.util.memoize.decorator.ret (cupy/util.cpp:1256)
  File "cupy/core/elementwise.pxi", line 405, in cupy.core.core._get_elementwise_kernel (cupy/core/core.cpp:32846)
  File "cupy/core/elementwise.pxi", line 12, in cupy.core.core._get_simple_elementwise_kernel (cupy/core/core.cpp:26224)
  File "cupy/core/elementwise.pxi", line 32, in cupy.core.core._get_simple_elementwise_kernel (cupy/core/core.cpp:26046)
  File "cupy/core/carray.pxi", line 87, in cupy.core.core.compile_with_cache (cupy/core/core.cpp:25733)
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 119, in compile_with_cache
    base = _empty_file_preprocess_cache[env] = preprocess('', options)
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 82, in preprocess
    pp_src = _run_nvcc(cmd, root_dir)
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 49, in _run_nvcc
    raise OSError(msg)
OSError: Failed to run `nvcc` command. Check PATH environment variable: [Errno 2] No such file or directory

**Comment by jinhang** [comment]
a new error!  For a long time! 
```
work-station@workstation-HP-Z440-Workstation:~/FCN/fcn-master/scripts$ python fcn_forward.py --img-files sample.jpg 
/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/home/work-station/FCN/fcn-master/scripts/sample.jpg:
 - resizing_scale: 0.894684897365
Traceback (most recent call last):
  File "fcn_forward.py", line 133, in <module>
    main()
  File "fcn_forward.py", line 124, in main
    img, label = forwarding.forward_img_file(img_file)
  File "fcn_forward.py", line 74, in forward_img_file
    fcn.util.draw_computational_graph([pred], output=psfile)
  File "/usr/local/lib/python2.7/dist-packages/fcn-3.0.0-py2.7.egg/fcn/util.py", line 112, in draw_computational_graph
    f.write(build_computational_graph(*args, **kwargs).dump())
TypeError: build_computational_graph() got an unexpected keyword argument 'output'

```

**Comment by wkentaro** [comment]
Fixed on my PC.
Please try following instruction.
https://github.com/wkentaro/fcn#for-beginners

You need to install latest fcn (`fcn==3.1.0`).

**Comment by wkentaro** [comment]
@jinhang Is this fixed?

**Comment by wkentaro** [comment]
Can i close this?

**Comment by jinhang** [comment]
hi, 
"For the answer to your question, I usually use python setup.py develop with virtualenv, so fcn.data_dir is always ~/fcn/data.
But if you install fcn with command pip or python setup.py install, it is /usr/local/lib/python2.7/fcn/_data or ~/.local/lib/python2.7/fcn/_data."
i don't understand your fcn.data_dir? you say the virtualenv,but how to use it?

**Comment by jinhang** [comment]
```
git clone https://github.com/wkentaro/fcn.git
cd fcn

python setup.py install
fcn_install_trained_data.py
```
`python setup.py install` and your `python setup.py develop` .what is this difference?
because it also can not run.so ,can you give me a new tutorial ? thanks wkentaro so much!

**Comment by wkentaro** [comment]
> i don't understand your fcn.data_dir?

It is defined here.
https://github.com/wkentaro/fcn/blob/master/fcn/__init__.py#L11

> you say the virtualenv,but how to use it?

If you are not familiar with [virtualenv](http://docs.python-guide.org/en/latest/dev/virtualenvs/), maybe you don't have to use it.

**Comment by wkentaro** [comment]
> python setup.py install and your python setup.py develop .what is this difference?

http://stackoverflow.com/questions/19048732/python-setup-py-develop-vs-install

**Comment by jinhang** [comment]
hi ,can you tell me the what is APC2015 dataset? I want use FCN model to detection in other dadaset?

**Comment by wkentaro** [comment]
>  APC2015 dataset?

That is Amazon Picking Chalenge 2015. http://amazonpickingchallenge.org/2015/index.shtml
The dataset is collected by myself and published as described here:
https://github.com/wkentaro/fcn/tree/master/examples/apc2015/dataset

**Comment by jinhang** [comment]
thank you very much!
